pod "AFNetworking", "~> 1.3.1"
pod "DTFoundation", "~> 1.4.4"
pod "MTPDF", "~> 0.0.5"
pod "StackBluriOS", "~> 0.0.1"
pod "JCTiledScrollView", :git => "https://github.com/jessedc/JCTiledScrollView.git"
